// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qamsyujczaxawzezaqmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhbXN5dWpjemF4YXd6ZXphcW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDI4NDEsImV4cCI6MjA1OTIxODg0MX0.yiOr0Sv6evuygR0Q_7LM3hmiWcLJ50w2yjlVr8Nddu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);